---
title: "scRNA-glioma-workflows: van Hijfte dataset - Sample Y"
author: 
  - Youri Hoogstrate
  - Levi van Hijfte
  - Santoesha A. Ghisai
date: "`r BiocStyle::doc_date()`"
version: "`r source('version.R'); project_version`"
---

```{r}
sample_name <- 'van Hijfte dataset - Sample Y'
```



```{r}
obj__van_hijfte__sample_y <- Seurat::Read10X(
  data.dir = "data/van_Hijfte__Sample_Y/filtered_feature_bc_matrix"
  ) |> 
  Seurat::CreateSeuratObject(min.cells = 3,
                             min.features = 200,
                             project = sample_name)
```

Adds fraction MT expression - should be put in a function
Same should be done for rRNA

```{r}
mito.features_object1 <- grep(pattern = "^MT-", x=rownames(x=obj__van_hijfte__sample_y), value=T)
percent.mito_object1 <- Matrix::colSums(x = Seurat::GetAssayData(object = obj__van_hijfte__sample_y, slot="counts")[mito.features_object1,]) / Matrix::colSums(x = Seurat::GetAssayData(object = obj__van_hijfte__sample_y, slot = "counts"))
obj__van_hijfte__sample_y[["percent.mito"]] <- percent.mito_object1
Seurat::VlnPlot(object = obj__van_hijfte__sample_y, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"), ncol = 3, pt.size = 0.01, group.by = "orig.ident") 
```

